import { Inter } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Nav from "@/components/Nav";

import "./globals.css";
import Carousel from "@/components/Carousel";
import Menu from "@/components/Menu";
import BurgerSlider from "@/components/product/BurgerSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <Nav />
          {children}
        </main>
        <Carousel />
        <BurgerSlider />
      </body>
    </html>
  );
}
